#
# Module manifest for module 'gs2o365'
#
# Generated by: Miso Stamenic
#
# Generated on: 09-23-2019
#
@{
    RootModule = 'gs2o365'
    ModuleVersion = '1.5'
    GUID = '47149120-0bcb-4f14-8d80-f4560107f85c'
    Author = 'Miso Stamenic'
    FunctionsToExport = @('*')
  }